import type { CapacityOffer, ShipperRfq } from './types';

export const CITIES = [
  'Dubai',
  'Jebel Ali',
  'Abu Dhabi',
  'Sharjah',
  'Riyadh',
  'Jeddah',
  'Dammam',
  'NEOM',
  'Singapore',
  'Jakarta',
  'Rotterdam',
  'Hamburg',
] as const;

/** Seed = customer RFQs on the FF desk (multi-lane demo; lane is a filter). */
export const initialRfqs: ShipperRfq[] = [
  {
    id: 'RFQ-1001',
    shipper: 'Gulf Electronics FZE',
    commodity: 'electronics',
    commodityLabel: 'Consumer electronics (HS 8517)',
    weightKg: 1200,
    volumeCbm: 8.5,
    pickupCity: 'Jebel Ali',
    dropCity: 'Riyadh',
    deadline: '2026-09-25',
    maxPriceUsd: 2800,
    hazmat: false,
    notes: 'Customer max sell $2,800 — desk to protect margin; air handoff OK if road ETA slips',
    status: 'open',
  },
  {
    id: 'RFQ-1002',
    shipper: 'MedSupply GCC',
    commodity: 'pharma',
    commodityLabel: 'Cold-chain pharma (HS 3004)',
    weightKg: 450,
    volumeCbm: 2.2,
    pickupCity: 'Dubai',
    dropCity: 'Jeddah',
    deadline: '2026-09-24',
    maxPriceUsd: 4200,
    hazmat: false,
    notes: '2–8°C · GDP carrier only — desk quoting shipper, buying soft space',
    status: 'open',
  },
  {
    id: 'RFQ-1003',
    shipper: 'Desert Dates Co.',
    commodity: 'perishable',
    commodityLabel: 'Fresh dates (HS 0804)',
    weightKg: 3500,
    volumeCbm: 14,
    pickupCity: 'Abu Dhabi',
    dropCity: 'Riyadh',
    deadline: '2026-09-26',
    maxPriceUsd: 1900,
    hazmat: false,
    notes: 'Tight sell ceiling — prefer healthy buy rate under $1,650',
    status: 'open',
  },
  {
    id: 'RFQ-1004',
    shipper: 'Al Noor Chemicals',
    commodity: 'hazmat',
    commodityLabel: 'Industrial solvents (HS 3814)',
    weightKg: 800,
    volumeCbm: 3.1,
    pickupCity: 'Sharjah',
    dropCity: 'Dammam',
    deadline: '2026-09-27',
    maxPriceUsd: 3500,
    hazmat: true,
    notes: 'UN-classed · only hazmat-licensed buy-side capacity — compliance first',
    status: 'open',
  },
  {
    id: 'RFQ-1005',
    shipper: 'NEOM Projects LLC',
    commodity: 'restricted',
    commodityLabel: 'Dual-use sensors (restricted)',
    weightKg: 220,
    volumeCbm: 1.0,
    pickupCity: 'Dubai',
    dropCity: 'NEOM',
    deadline: '2026-09-28',
    maxPriceUsd: 5500,
    hazmat: false,
    notes: 'Export-control screening at UAE–KSA border — desk may veto cheap buy options',
    status: 'open',
  },
  {
    id: 'RFQ-1006',
    shipper: 'Riyadh Retail Hub',
    commodity: 'general',
    commodityLabel: 'FMCG mixed pallet (HS 2106)',
    weightKg: 2100,
    volumeCbm: 11,
    pickupCity: 'Jebel Ali',
    dropCity: 'Riyadh',
    deadline: '2026-09-26',
    maxPriceUsd: 2200,
    hazmat: false,
    notes: 'Routine quoting lane — build buy/sell options with visible margin',
    status: 'open',
  },
  {
    id: 'RFQ-1007',
    shipper: 'ASEAN Components Pte',
    commodity: 'electronics',
    commodityLabel: 'PCB assemblies (HS 8534)',
    weightKg: 900,
    volumeCbm: 4.5,
    pickupCity: 'Singapore',
    dropCity: 'Jakarta',
    deadline: '2026-09-27',
    maxPriceUsd: 2400,
    hazmat: false,
    notes: 'Example SEA lane — same desk choreography, different corridor filter',
    status: 'open',
  },
  {
    id: 'RFQ-1008',
    shipper: 'Nordic Retail BV',
    commodity: 'general',
    commodityLabel: 'Retail replenishment (HS 6302)',
    weightKg: 2800,
    volumeCbm: 16,
    pickupCity: 'Rotterdam',
    dropCity: 'Hamburg',
    deadline: '2026-09-26',
    maxPriceUsd: 1800,
    hazmat: false,
    notes: 'Example EU short-haul lane — desk buy/sell/margin still applies',
    status: 'open',
  },
];

/** Seed = buy-side soft space / schedules the desk can purchase. */
export const initialCapacity: CapacityOffer[] = [
  {
    id: 'CAP-501',
    carrier: 'RegionalFleet Logistics',
    carrierAgent: 'SourcingAgent-RegionalFleet',
    mode: 'road',
    lane: 'Jebel Ali → Riyadh',
    pickupCity: 'Jebel Ali',
    dropCity: 'Riyadh',
    availableWeightKg: 8000,
    availableVolumeCbm: 40,
    rateMinUsd: 1600,
    rateMaxUsd: 2100,
    departureWindow: '2026-09-23 06:00–14:00 GST',
    etaHours: 18,
    reliability: 92,
    docsOk: true,
    restrictedOk: false,
    hazmatOk: false,
    status: 'available',
    kind: 'published',
    source: 'seed',
    confidence: 'carrier_published',
    notes: 'Buy-side soft space — published leftover',
  },
  {
    id: 'CAP-502',
    carrier: 'Aramex Freight (demo)',
    carrierAgent: 'SourcingAgent-Aramex',
    mode: 'road+air',
    lane: 'Dubai → Jeddah (air handoff DXB)',
    pickupCity: 'Dubai',
    dropCity: 'Jeddah',
    availableWeightKg: 2000,
    availableVolumeCbm: 12,
    rateMinUsd: 3200,
    rateMaxUsd: 4100,
    departureWindow: '2026-09-23 10:00–16:00 GST',
    etaHours: 10,
    reliability: 96,
    docsOk: true,
    restrictedOk: false,
    hazmatOk: false,
    status: 'available',
    kind: 'published',
    source: 'seed',
    confidence: 'carrier_published',
  },
  {
    id: 'CAP-503',
    carrier: 'GulfHaul Express',
    carrierAgent: 'SourcingAgent-GulfHaul',
    mode: 'road',
    lane: 'Abu Dhabi → Riyadh',
    pickupCity: 'Abu Dhabi',
    dropCity: 'Riyadh',
    availableWeightKg: 12000,
    availableVolumeCbm: 55,
    rateMinUsd: 1400,
    rateMaxUsd: 1850,
    departureWindow: '2026-09-24 04:00–12:00 GST',
    etaHours: 20,
    reliability: 88,
    docsOk: true,
    restrictedOk: false,
    hazmatOk: false,
    status: 'available',
    kind: 'published',
    source: 'seed',
    confidence: 'carrier_published',
  },
  {
    id: 'CAP-504',
    carrier: 'SafeChem Transport',
    carrierAgent: 'SourcingAgent-SafeChem',
    mode: 'road',
    lane: 'Sharjah → Dammam',
    pickupCity: 'Sharjah',
    dropCity: 'Dammam',
    availableWeightKg: 5000,
    availableVolumeCbm: 25,
    rateMinUsd: 2400,
    rateMaxUsd: 3200,
    departureWindow: '2026-09-24 08:00–18:00 GST',
    etaHours: 16,
    reliability: 94,
    docsOk: true,
    restrictedOk: false,
    hazmatOk: true,
    status: 'available',
    kind: 'published',
    source: 'seed',
    confidence: 'carrier_published',
  },
  {
    id: 'CAP-505',
    carrier: 'BudgetWheels GCC',
    carrierAgent: 'SourcingAgent-BudgetWheels',
    mode: 'road',
    lane: 'Dubai → NEOM',
    pickupCity: 'Dubai',
    dropCity: 'NEOM',
    availableWeightKg: 3000,
    availableVolumeCbm: 18,
    rateMinUsd: 2800,
    rateMaxUsd: 3600,
    departureWindow: '2026-09-25 05:00–11:00 GST',
    etaHours: 22,
    reliability: 71,
    docsOk: false,
    restrictedOk: false,
    hazmatOk: false,
    status: 'available',
    kind: 'published',
    source: 'seed',
    confidence: 'carrier_published',
    notes: 'Cheap buy but missing border docs — expect compliance veto',
  },
  {
    id: 'CAP-506',
    carrier: 'SkyBridge Cargo',
    carrierAgent: 'SourcingAgent-SkyBridge',
    mode: 'air',
    lane: 'Dubai → Riyadh (air)',
    pickupCity: 'Dubai',
    dropCity: 'Riyadh',
    availableWeightKg: 1500,
    availableVolumeCbm: 6,
    rateMinUsd: 3800,
    rateMaxUsd: 5200,
    departureWindow: '2026-09-23 14:00–20:00 GST',
    etaHours: 6,
    reliability: 97,
    docsOk: true,
    restrictedOk: true,
    hazmatOk: false,
    status: 'available',
    kind: 'schedule',
    source: 'seed',
    confidence: 'schedule',
    notes: 'Schedule row — not leftover soft space',
  },
  {
    id: 'CAP-507',
    carrier: 'Peninsula Linehaul',
    carrierAgent: 'SourcingAgent-Peninsula',
    mode: 'road',
    lane: 'Jebel Ali → Riyadh',
    pickupCity: 'Jebel Ali',
    dropCity: 'Riyadh',
    availableWeightKg: 6000,
    availableVolumeCbm: 32,
    rateMinUsd: 1750,
    rateMaxUsd: 2300,
    departureWindow: '2026-09-23 12:00–20:00 GST',
    etaHours: 19,
    reliability: 90,
    docsOk: true,
    restrictedOk: false,
    hazmatOk: false,
    status: 'available',
    kind: 'published',
    source: 'seed',
    confidence: 'carrier_published',
  },
  {
    id: 'CAP-508',
    carrier: 'ClearPath Controlled',
    carrierAgent: 'SourcingAgent-ClearPath',
    mode: 'road+air',
    lane: 'Dubai → NEOM (controlled goods)',
    pickupCity: 'Dubai',
    dropCity: 'NEOM',
    availableWeightKg: 800,
    availableVolumeCbm: 4,
    rateMinUsd: 4200,
    rateMaxUsd: 5400,
    departureWindow: '2026-09-25 09:00–15:00 GST',
    etaHours: 14,
    reliability: 95,
    docsOk: true,
    restrictedOk: true,
    hazmatOk: false,
    status: 'available',
    kind: 'published',
    source: 'seed',
    confidence: 'carrier_published',
  },
  {
    id: 'CAP-509',
    carrier: 'Straits Roadlink',
    carrierAgent: 'SourcingAgent-Straits',
    mode: 'road',
    lane: 'Singapore → Jakarta',
    pickupCity: 'Singapore',
    dropCity: 'Jakarta',
    availableWeightKg: 5000,
    availableVolumeCbm: 28,
    rateMinUsd: 1400,
    rateMaxUsd: 2100,
    departureWindow: '2026-09-24 08:00–18:00 SGT',
    etaHours: 36,
    reliability: 88,
    docsOk: true,
    restrictedOk: false,
    hazmatOk: false,
    status: 'available',
    kind: 'published',
    source: 'seed',
    confidence: 'carrier_published',
    notes: 'Demo SEA capacity for multi-lane desk',
  },
  {
    id: 'CAP-510',
    carrier: 'Benelux Haulage',
    carrierAgent: 'SourcingAgent-Benelux',
    mode: 'road',
    lane: 'Rotterdam → Hamburg',
    pickupCity: 'Rotterdam',
    dropCity: 'Hamburg',
    availableWeightKg: 9000,
    availableVolumeCbm: 45,
    rateMinUsd: 1100,
    rateMaxUsd: 1600,
    departureWindow: '2026-09-24 06:00–14:00 CET',
    etaHours: 8,
    reliability: 92,
    docsOk: true,
    restrictedOk: false,
    hazmatOk: false,
    status: 'available',
    kind: 'published',
    source: 'seed',
    confidence: 'carrier_published',
    notes: 'Demo EU capacity for multi-lane desk',
  },
];

export const AGENT_META: Record<
  string,
  { label: string; color: string; short: string }
> = {
  DeskAgent: { label: 'Desk', color: '#38bdf8', short: 'DESK' },
  ShipperAgent: { label: 'Desk', color: '#38bdf8', short: 'DESK' },
  'SourcingAgent-RegionalFleet': {
    label: 'Sourcing-RegionalFleet',
    color: '#a78bfa',
    short: 'SRC',
  },
  'SourcingAgent-Aramex': {
    label: 'Sourcing-Aramex',
    color: '#c084fc',
    short: 'SRC',
  },
  'SourcingAgent-GulfHaul': {
    label: 'Sourcing-GulfHaul',
    color: '#a78bfa',
    short: 'SRC',
  },
  'SourcingAgent-SafeChem': {
    label: 'Sourcing-SafeChem',
    color: '#a78bfa',
    short: 'SRC',
  },
  'SourcingAgent-BudgetWheels': {
    label: 'Sourcing-BudgetWheels',
    color: '#a78bfa',
    short: 'SRC',
  },
  'SourcingAgent-SkyBridge': {
    label: 'Sourcing-SkyBridge',
    color: '#a78bfa',
    short: 'SRC',
  },
  'SourcingAgent-Peninsula': {
    label: 'Sourcing-Peninsula',
    color: '#a78bfa',
    short: 'SRC',
  },
  'SourcingAgent-ClearPath': {
    label: 'Sourcing-ClearPath',
    color: '#a78bfa',
    short: 'SRC',
  },
  'SourcingAgent-Straits': {
    label: 'Sourcing-Straits',
    color: '#a78bfa',
    short: 'SRC',
  },
  'SourcingAgent-Benelux': {
    label: 'Sourcing-Benelux',
    color: '#a78bfa',
    short: 'SRC',
  },
  // Legacy CarrierAgent-* keys still resolve for ingest-mapped rows
  'CarrierAgent-RegionalFleet': {
    label: 'Sourcing-RegionalFleet',
    color: '#a78bfa',
    short: 'SRC',
  },
  'CarrierAgent-Aramex': {
    label: 'Sourcing-Aramex',
    color: '#c084fc',
    short: 'SRC',
  },
  'CarrierAgent-GulfHaul': {
    label: 'Sourcing-GulfHaul',
    color: '#a78bfa',
    short: 'SRC',
  },
  'CarrierAgent-SafeChem': {
    label: 'Sourcing-SafeChem',
    color: '#a78bfa',
    short: 'SRC',
  },
  'CarrierAgent-BudgetWheels': {
    label: 'Sourcing-BudgetWheels',
    color: '#a78bfa',
    short: 'SRC',
  },
  'CarrierAgent-SkyBridge': {
    label: 'Sourcing-SkyBridge',
    color: '#a78bfa',
    short: 'SRC',
  },
  'CarrierAgent-Peninsula': {
    label: 'Sourcing-Peninsula',
    color: '#a78bfa',
    short: 'SRC',
  },
  'CarrierAgent-ClearPath': {
    label: 'Sourcing-ClearPath',
    color: '#a78bfa',
    short: 'SRC',
  },
  'CarrierAgent-Straits': {
    label: 'Sourcing-Straits',
    color: '#a78bfa',
    short: 'SRC',
  },
  'CarrierAgent-Benelux': {
    label: 'Sourcing-Benelux',
    color: '#a78bfa',
    short: 'SRC',
  },
  PricingAgent: { label: 'Pricing', color: '#34d399', short: 'PRICE' },
  MatchAgent: { label: 'Pricing', color: '#34d399', short: 'PRICE' },
  ComplianceAgent: { label: 'Compliance', color: '#fbbf24', short: 'COMP' },
  ExceptionAgent: { label: 'Exception', color: '#f87171', short: 'EXC' },
  System: { label: 'System', color: '#94a3b8', short: 'SYS' },
};
